application: bib2yaml
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /style
  static_dir: style

- url: .*
  script: main.application
  
libraries:
- name: webapp2
  version: "2.5.2"